name: Basic
on: workflow_dispatch
jobs:
  gradle:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Execute Gradle build
        run: ./gradlew build

