name: Publish
on: workflow_dispatch
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # Only write to the cache for builds on the 'master' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Execute Gradle build
        run: ./gradlew publish

      - name: Archive publication
        uses: actions/upload-artifact@v3
        with:
          name: plugin-publication
          path: build/repo/dev/jacomet/gradle/plugins/logging-capabilities
